# Generated by Django 4.2.7 on 2023-12-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cena')),
                ('picture', models.ImageField(upload_to='', verbose_name='Zdjęcie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.categoryofproduct', verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Adres dostawy')),
                ('products_list', models.CharField(max_length=150, verbose_name='Lista produktów')),
                ('date_order', models.DateTimeField(verbose_name='Data zamówienia')),
                ('date_payment', models.DateTimeField(verbose_name='Termin płatności')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sumaryczna cena')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Klient')),
            ],
        ),
    ]
